customer: dataoffice

aml_experiment_details:
  compute_name: dataoffice-cluster
  env_name: baas-environment
  env_version: 1
  src_dir: "."

metadata_pipeline:
  datastore: "nieuw_panorama_beelden_geo360"
  tagged_data: True
  inputs:
    coco_annotations: "geo30-coco.json"
    images: "selectie_original/images/val"
  outputs:
    yolo_annotations: "selectie_original/labels/val"  # yolo labels are overwritten with every new run
    image_width: 8000
    image_height: 40000
    metadata: "metadata.json"
    coco_annotations: "coco.json"
  flags:
    # Possible values: NONE, CONVERT_AZURE_COCO_TO_YOLO, CONVERT_AZURE_COCO_TO_COCO, CREATE_METADATA
    - CONVERT_AZURE_COCO_TO_YOLO
    - CONVERT_AZURE_COCO_TO_COCO

performance_evaluation_pipeline:
  datastore: "nieuw_panorama_beelden_geo360"
  inputs:
    yolo_dataset: "selectie_original"
    coco_annotations: "metadata-pipeline/selectie_original_coco_labels/coco.json"
    model_name: "dataoffice_model"
    model_version: "1"
  model_parameters:
    imgsz: 2048
    name: "yolo_exp_1"
    save_blurred_image: True
    conf_thres: 0.001
  metrics_metadata:
    image_height: 4000
    image_width: 8000
    image_area: 32000000

training_pipeline:
  model_parameters:
    img_size: 2048
    batch_size: 8
    epochs: 2
  inputs:
    training_data: "azureml://FOLDER_PATH_TO_TRAINING_DATA"
    model_weights: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
  outputs:
    trained_model: "azureml://FOLDER_PATH_WHERE_STORE_TRAINED_MODEL"
  flags:
    # Possible values: NONE (in case no flag is needed), STORE_MODEL
    - NONE

pre_inference_pipeline:
  inputs:
    number_of_batches: 1

inference_pipeline:
  model_name: "dataoffice_model"
  model_version: "1"
  model_parameters:
    imgsz: 2048
    save_txt: True
    exist_ok: True
    skip_evaluation: True
    save_blurred_image: True
    batch_size: 4
    conf_thres: 0.0001

database_parameters:
  db_hostname: "psql-flexi-blur-prd-weu-cou-01.postgres.database.azure.com"
  db_username: "aml-compute-cvp-p"
  db_name: "blur"

logging:
  loglevel_own: "WARNING"  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "blurring_as_a_service"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "APPLICATION_INSIGHTS_INSTRUMENTATION_KEY"