customer: dataoffice

aml_experiment_details:
experiment_name: "baas_dataoffice"
  compute_name: gpu-inference-cluster
  env_name: baas-environment
  env_version: 1  # Replace with the latest version
  src_dir: "."

metadata_pipeline:
  datastore: "nieuw_panorama_beelden_geo360"
  tagged_data: True
  inputs:
    coco_annotations: "geo30-coco.json"
    images: "selectie_original/images/val"
  outputs:
    yolo_annotations: "selectie_original/labels/val"  # yolo labels are overwritten with every new run
    image_width: "8000"
    image_height: "4000"
    metadata: "metadata.json"
    coco_annotations: "coco.json"
  flags:
    # Possible values: NONE, CONVERT_AZURE_COCO_TO_YOLO, CONVERT_AZURE_COCO_TO_COCO, CREATE_METADATA
    - CONVERT_AZURE_COCO_TO_YOLO
    - CONVERT_AZURE_COCO_TO_COCO

count_images_pipeline:
  inputs: 
    datastore: "inference_test"
    input_rel_path: "datasets/kavel10_kempkes_geo360_sampled_panos_test" 

pre_inference_pipeline:
  inputs: 
    datastore: "inference_test"
    input_rel_path: "datasets/kavel10_kempkes_geo360_sampled_panos_test"
    exclude_list_file: "files_not_to_process.csv"  # Column of file names with header "file"; use "None" for no exclude list
  outputs:
    datastore: "inference_test"
    inference_queue_rel_path: "inference_queue"  # Where to store batch files
  number_of_batches: 1

inference_pipeline:
  model_params:
    batch_size: 1
    img_size: 2048
    conf: 0.01
  inputs:
    datastore: "inference_test"
    inference_queue_rel_path: "inference_queue"  # Output of pre-inference pipeline
    model_name: "dataoffice_model"
    model_version: "2"
  outputs:
    datastore: "inference_test"
    output_rel_path: "inference/baas_test"
    detections_subfolder: ""
    labels_subfolder: ""
  target_classes: []
  sensitive_classes: [0, 1]
  target_classes_conf: null  # null means conf is taken from model_params
  sensitive_classes_conf: null  # null means conf is taken from model_params
  output_image_size: null  # null means keep original size
  save_detection_images: True
  save_detection_labels: False
  save_all_images: True  # If True, all images will be saved regardless of whether they contain target class objects
  database_parameters:
    db_hostname: "psql-flexi-blur-ont-weu-esy-01.postgres.database.azure.com"
    db_username: "aml-compute-cvo-p"
    db_name: "blur"
    client_id: "" # AML User assigned identity Client ID

sampling_parameters:
  quality_check_sample_size: 10
  conf_score_threshold: 0.0005
  sampling_ratio: 1

api_endpoint:
  endpoint_name: "endpt-cvt-baas-2"
  deployment_color: "blue"  # blue or green
  instance_type: "Standard_NC4as_T4_v3"
  model_name: "OOR-model"
  model_version: "2"

logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "blurring_as_a_service", "cvtoolkit",
                 "aml_interface", "evaluate_with_cvt_metrics", "validate_model",
                 "evaluate_with_coco", "detect_and_blur_sensitive_data",
                 "inference_pipeline", "move_files", "split_workload",
                 "workload_splitter", "smart_sampling", "api_endpoint",
                 "count_images"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: INFO
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "APPLICATION_INSIGHTS_CONNECTION_STRING"
