aml_experiment_details:
  compute_name: cvt-compute
  env_name: cvt_environment
  env_version: 1
  src_dir: "."

metadata_pipeline:
  inputs:
    coco_annotations: "azureml:NAMED_ASSET_URI_CONTAINING_COCO_ANNOTATIONS"
    images_path: "azureml://FOLDER_PATH_CONTAINING_THE_IMAGES"
  outputs:
    labels_path: "azureml://FOLDER_PATH_WHERE_STORE_YOLO_LABELS"
    metadata_path: "azureml://FOLDER_PATH_WHERE_STORE_METADATA"
  flags:
    # Possible values: NONE (in case no flag is needed), CREATE_ENVIRONMENT, CONVERT_COCO_TO_YOLO, CREATE_METADATA
    - CREATE_ENVIRONMENT
    - CONVERT_COCO_TO_YOLO
    - CREATE_METADATA

training_pipeline:
  inputs:
    training_data: "azureml://FOLDER_PATH_WHERE_TRAINING_DATA_IS_LOCATED"
  flags:
    # Possible values: NONE (in case no flag is needed), CREATE_ENVIRONMENT
    - NONE

inference_pipeline:
  inputs:
    data_to_blur: "azureml://PATH_TO_DATA_TO_BLUR"
    model: "azureml://PATH_TO_MODEL_FILE"
  outputs:
    results_path: "azureml://PATH_TO_WHERE_STORE_RESULTS"
  flags:
    # Possible values: NONE (in case no flag is needed)
    - NONE

logging:
  loglevel_own: "WARNING"  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "blurring_as_a_service"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
