aml_experiment_details:
  compute_name: cvt-compute
  env_name: cvt_environment
  env_version: 1
  src_dir: "."

metadata_pipeline:
  inputs:
    coco_annotations: "azureml:NAMED_ASSET_URI_CONTAINING_COCO_ANNOTATIONS"
    images_path: "azureml://FOLDER_PATH_CONTAINING_THE_IMAGES"
  outputs:
    labels_path: "azureml://FOLDER_PATH_WHERE_STORE_YOLO_LABELS"
    metadata_path: "azureml://FOLDER_PATH_WHERE_STORE_METADATA"
  flags:
    # Possible values: NONE (in case no flag is needed), CONVERT_COCO_TO_YOLO, CREATE_METADATA
    - CONVERT_COCO_TO_YOLO
    - CREATE_METADATA

training_pipeline:
  model_parameters:
    img_size: 2048
    batch_size: 8
    epochs: 2
  inputs:
    training_data: "azureml://FOLDER_PATH_TO_TRAINING_DATA"
    model_weights: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
  outputs:
    trained_model: "azureml://FOLDER_PATH_WHERE_STORE_TRAINED_MODEL"
  flags:
    # Possible values: NONE (in case no flag is needed), STORE_MODEL
    - NONE

workload_distribution_pipeline:
  inputs:
    data_folder: "azureml://FOLDER_PATH_TO_IMAGES_FOLDER"
    number_of_batches: 4
  outputs:
    results_folder: "azureml://FOLDER_PATH_WHERE_STORE_WORKLOAD_FILES"

inference_pipeline:
  model_parameters:
    imgsz: 4000
    save_txt: True
    exist_ok: True
    save_csv: True
    save_blurred_image: True
    batch_size: 1
  inputs:
    root_folder: "azureml://FOLDER_PATH_TO_IMAGES_FOLDER"
    files_to_blur: "azureml://FILE_WITH_RELATIVE_PATHS_OF_BLUR_IMAGES"
    model: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
  outputs:
    yolo_yaml_file: "azureml://FOLDER_PATH_WHERE_STORE_YAML_FILE_USED_BY_YOLO"
    results_path: "azureml://FOLDER_PATH_WHERE_STORE_BLURRED_IMAGES"

move_data_pipeline:
  customers:
    - example-customer
  input_container_root: "azureml://subscriptions/{subscription}/resourcegroups/{resourcegroup}/workspaces/{workspace}/datastores/{datastore_name}/paths/"
  output_container_root: "azureml://subscriptions/{subscription}/resourcegroups/{resourcegroup}/workspaces/{workspace}/datastores/{datastore_name}/paths/"

performance_evaluation_pipeline:
  inputs:
    validation_images_path: "azureml://FOLDER_PATH_TO_IMAGES_FOLDER"
    annotations_for_coco_metrics: "azureml://FILE_PATH_TO_COCO_format_annotations_for_COCO_evaluation"
    model: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
    annotations_for_custom_metrics: "azureml://FILE_PATH_TO_Azure_COCO_format_tagged_annotations_for_custom_evaluation"
  outputs:
    yolo_yaml_file: "azureml://FOLDER_PATH_WHERE_STORE_YAML_FILE_USED_BY_YOLO"
    yolo_validation_output: "azureml://FOLDER_PATH_WHERE_STORE_VALIDATION_OUTPUT"
  yolo_run_name: "name of the yolo run, type string. More information in the README.md"

logging:
  loglevel_own: "WARNING"  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "blurring_as_a_service"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
