customer: dataoffice

aml_experiment_details:
  compute_name: gpu-blurring-model
  env_name: baas-environment
  env_version: 45
  src_dir: "."

metadata_pipeline:
  datastore: "nieuw_panorama_beelden_geo360"
  tagged_data: True
  inputs:
    coco_annotations: "geo30-coco.json"
    images: "selectie_original/images/val"
  outputs:
    yolo_annotations: "selectie_original/labels/val"  # yolo labels are overwritten with every new run
    image_width: 8000
    image_height: 40000
    metadata: "metadata.json"
    coco_annotations: "coco.json"
  flags:
    # Possible values: NONE, CONVERT_AZURE_COCO_TO_YOLO, CONVERT_AZURE_COCO_TO_COCO, CREATE_METADATA
    - CONVERT_AZURE_COCO_TO_YOLO
    - CONVERT_AZURE_COCO_TO_COCO

performance_evaluation_pipeline:
  datastore: "nieuw_panorama_beelden_geo360"
  inputs:
    yolo_dataset: "selectie_original"
    coco_annotations: "metadata-pipeline/selectie_original_coco_labels/coco.json"
    model_name: "dataoffice_model"
    model_version: "1"
  model_parameters:
    imgsz: 2048
    name: "yolo_exp_1"
    save_blurred_image: True
    conf_thres: 0.001
    no_inverted_colors: True
  metrics_metadata:
    image_height: 4000
    image_width: 8000
    image_area: 32000000

training_pipeline:
  model_parameters:
    img_size: 2048
    batch_size: 8
    epochs: 2
  inputs:
    training_data: "azureml://FOLDER_PATH_TO_TRAINING_DATA"
    model_weights: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
  outputs:
    trained_model: "azureml://FOLDER_PATH_WHERE_STORE_TRAINED_MODEL"
  flags:
    # Possible values: NONE (in case no flag is needed), STORE_MODEL
    - NONE

pre_inference_pipeline:
  datastore_input: "dataoffice_input_structured"
  datastore_input_path: "2024-10-23_09_03_18"
  datastore_output: "dataoffice_input_structured"
  inputs:
    number_of_batches: 1

inference_pipeline:
  model_params:
    batch_size: 4
    img_size: 2048
    conf: 0.0001
  inputs:
    datastore_path: "dataoffice_input"
    inference_data_rel_path: "."
    model_name: "yolo11m_orbs_lilac_spaceship-2"
    model_version: "1"
  outputs:
    datastore_path: "dataoffice_output"  # empty string "" means same as input datastore
    output_rel_path: "2023/output_blurred"
    detections_subfolder: ""
    labels_subfolder: ""
  sahi_params:
    model_type: "ultralytics"
    slice_height: 2048
    slice_width: 2048
    overlap_height_ratio: 0.2
    overlap_width_ratio: 0.2
  target_classes: []
  sensitive_classes: [0, 1]
  target_classes_conf: null  # null means conf is taken from model_params
  sensitive_classes_conf: null  # null means conf is taken from model_params
  output_image_size: null  # null means keep original size
  save_detection_images: True
  save_detection_labels: True
  save_all_images: True  # If True, all images will be saved regardless of whether they contain target class objects
  use_sahi: False
  database_parameters:
    db_hostname: "psql-flexi-blur-ont-weu-esy-01.postgres.database.azure.com"
    db_username: "aml-compute-cvo-p"
    db_name: "blur"
    client_id: "" # AML User assigned identity Client ID

sampling_parameters:
  quality_check_sample_size: 10
  conf_score_threshold: 0.0005
  sampling_ratio: 1


logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "blurring_as_a_service", "yolov5", "cvtoolkit", "aml_interface",
                 "evaluate_with_cvt_metrics", "validate_model", "evaluate_with_coco", "detect_and_blur_sensitive_data",
                 "move_files", "split_workload", "smart_sampling"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: INFO
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "APPLICATION_INSIGHTS_CONNECTION_STRING"
