aml_experiment_details:
  compute_name: cvt-compute
  env_name: cvt_environment
  env_version: 1
  src_dir: "."

metadata_pipeline:
  inputs:
    coco_annotations: "azureml:NAMED_ASSET_URI_CONTAINING_COCO_ANNOTATIONS"
    images_path: "azureml://FOLDER_PATH_CONTAINING_THE_IMAGES"
  outputs:
    labels_path: "azureml://FOLDER_PATH_WHERE_STORE_YOLO_LABELS"
    metadata_path: "azureml://FOLDER_PATH_WHERE_STORE_METADATA"
  flags:
    # Possible values: NONE (in case no flag is needed), CREATE_ENVIRONMENT, CONVERT_COCO_TO_YOLO, CREATE_METADATA
    - CREATE_ENVIRONMENT
    - CONVERT_COCO_TO_YOLO
    - CREATE_METADATA

training_pipeline:
  inputs:
    training_data: "azureml://FOLDER_PATH_TO_TRAINING_DATA"
    model_weights: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
  outputs:
    trained_model: "azureml://FOLDER_PATH_WHERE_STORE_TRAINED_MODEL"
  flags:
    # Possible values: NONE (in case no flag is needed), CREATE_ENVIRONMENT, STORE_MODEL
    - NONE

inference_pipeline:
  inputs:
    data_to_blur: "azureml://FOLDER_PATH_TO_IMAGES_FOLDER"
    model: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
  outputs:
    results_path: "azureml://FOLDER_PATH_WHERE_STORE_BLURRED_IMAGES"


performance_evaluation_pipeline:
  inputs:
    validation_images_path: "azureml://FOLDER_PATH_TO_IMAGES_FOLDER"
    annotations_for_coco_metrics: "azureml://FILE_PATH_TO_COCO_format_annotations_for_COCO_evaluation"
    model: "azureml://NAMED_ASSET_URI_MODEL_WEIGHTS_FILE"
    annotations_for_custom_metrics: "azureml://FILE_PATH_TO_Azure_COCO_format_tagged_annotations_for_custom_evaluation"
  outputs:
    yolo_yaml_file: "azureml://FOLDER_PATH_WHERE_STORE_YAML_FILE_USED_BY_YOLO"
    yolo_validation_output: "azureml://FOLDER_PATH_WHERE_STORE_VALIDATION_OUTPUT"
  experiment_name: "when we run an experiment a new folder is created by yolo. e.g. run_with_sample. 
                  This fails when running multiple experiments with the same name, because yolo automatically 
                  creates a new experiment_name if experiment_name folder already exists. 
                  e.g. it creates run_with_sample_2 on the fly, while the subsequent tasks will be using the content 
                  of the run_with_sample folder."

logging:
  loglevel_own: "WARNING"  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "blurring_as_a_service"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
