[tool.poetry]
name = "blurring_as_a_service"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.9"
pandas = ">=1.1.4"
GitPython = ">=3.1.30"
ipython = {version = "^8.8.0", source = "PyPI"}
matplotlib = ">=3.2.2"
numpy = ">=1.18.5"
opencv-python = ">=4.1.1"
Pillow = ">=7.1.2"
psutil = {version = "^5.9.4", source = "PyPI"}
PyYAML = ">=5.3.1"
requests = ">=2.23.0"
scipy = ">=1.4.1"
thop = ">=0.1.1"
torch = ">=1.7.0"
torchvision = ">=0.8.1"
tqdm = ">=4.64.0"
tensorboard = ">=2.4.1"
seaborn = ">=0.11.0"
pre-commit = {version = "^2.21.0", source = "PyPI"}
pytest = {version = "^7.2.1", source = "PyPI"}
azure-ai-ml = {version = "^1.2.0", source = "PyPI"}
mldesigner = {version = "^0.1.0-beta.9", source = "PyPI"}
dataclass-wizard = {version = "^0.22.2", source = "PyPI"}
python-geohash = {version = "^0.8.5", source = "PyPI"}
azure-identity = {version = "^1.12.0", source = "PyPI"}
pycocotools = {version = "^2.0.6", source="PyPI"}
cryptography = {version = "<39.0.0", source = "PyPI"}
markdown-it-py = {version="^2.2.0", source = "PyPI"}
joblib = {version="^1.2.0", source = "PyPI"}
mss = {version="^7.0.1", source = "PyPI"}
setuptools = ">=65.5.1"
panorama = {git = "https://github.com/Computer-Vision-Team-Amsterdam/panorama.git", tag = "v0.2.2"}
packaging = "20.0"

[tool.poetry.dev-dependencies]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
